### ISSUE TITLE
Syntax Errors when running examples

### ISSUE THREAD

**Issue by kcdc29** [jnederlo/dfs_optimizers#4]
Hello, I'm new to Python so still working my way through.  After installing all dependencies and CPLEX, I run and get a syntax error on line 20 from what looks like an errant if in the output_filepath 

f'nhl/example_output_draftkings.csv'

After I remove that, it runs, but gets stuck when asking me DraftKings or FanDuel (1 or 2).  After selecting 1 (or 2), it prints "try again".

**Comment by jnederlo** [comment]
I was using a format string on that line, so you would need to use python 3.6 to run it. I just changed that, so it should be fine now. 

Regarding "try again", you most likely put in the wrong number, as that's the only reason it would print that.

**Comment by kcdc29** [comment]
<img width="483" alt="Capture" src="https://user-images.githubusercontent.com/55777962/66231906-d8edd100-e6a4-11e9-99d7-abf51337012c.PNG">
Still getting hung up there.  redownloaded everything and still getting.  somewhat strange

**Comment by jnederlo** [comment]
Unfortunately because it’s windows I can’t be of much help as to what is happening. I would just hard code the result in instead of getting the input from the command line. Set the variable to a string of 1 or 2 yourself. Hopefully that fixes it.
